version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/python
          push: true
          tags: ["${CI_COMMIT_SHA}", "latest"]
          dockerfile: Dockerfile
          context: .
          args:
          - API_TOKEN=dckr_pat_rTYiSBR4r_dKuNOb4QAQ6l0ETh4
  
