version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/python
          push: true
          tags: [b'${CI_COMMIT_SHA}", "latest"]
          dockerfile: ./Dockerfile
          context: .
          args:
          - API_TOKEN=foobar
